// compliment.js
export const compliments = [
  "You light up every room you walk into.",
  "Your smile could start a revolution.",
  "You bring out the best in people.",
  "You're stronger than you think.",
  "You're like a breath of fresh air.",
  "You're proof that kindness still exists.",
  "You have a contagious laugh.",
  "You radiate good energy.",
  "Your presence is calming.",
  "You’re someone others can always count on.",
  "You're effortlessly cool.",
  "You're a walking ray of sunshine.",
  "You're a great listener.",
  "You make people feel seen.",
  "You're full of good ideas.",
  "You make things better just by being there.",
  "You're inspiring without even trying.",
  "You lead with heart and soul.",
  "You're genuinely thoughtful.",
  "You’ve got a heart of gold.",
  "You have excellent taste.",
  "You’re more powerful than your doubts.",
  "You deserve every good thing coming your way.",
  "You're not just smart, you're wise.",
  "You’ve got great energy.",
  "Your perspective is valuable.",
  "You have a rare kind of authenticity.",
  "You’ve already made someone’s day—just by being you.",
  "You make people feel at home.",
  "You carry yourself with quiet strength.",
  "You're magnetic in the best way.",
  "You're a beautiful mix of calm and chaos.",
  "You make challenges look easy.",
  "You glow with confidence.",
  "You’re full of hidden talents.",
  "You have the kind of smile that makes hearts race.",
  "You're so real, it's refreshing.",
  "Your existence matters deeply.",
  "You uplift everyone around you.",
  "You're a solid 11/10.",
  "You’ve got the kind of vibe money can’t buy.",
  "You’ve grown so much—be proud of that.",
  "You're the reason someone believes in magic.",
  "You're exactly what this world needs more of.",
  "You’re always leveling up.",
  "You're consistent, dependable, and golden.",
  "You're emotionally intelligent—rare AF.",
  "You're that friend people brag about having.",
  "You’ve got grace, grit, and glow.",
  "You turn setbacks into comebacks.",
];
