// roast.js
export const roasts = [
  "You're the reason shampoo has instructions.",
  "You're not stupid; you just have bad luck thinking.",
  "If I had a dollar for every smart thing you said, I’d be broke.",
  "You're like a cloud—when you disappear, it's a beautiful day.",
  "You bring everyone so much joy… when you leave the room.",
  "You have something on your chin… no, the third one down.",
  "You have something on your face… humility. Just kidding.",
  "You're not ugly, but you're not exactly photogenic either.",
  "You're not the sharpest knife in the drawer—more like a spoon.",
  "You have something special. A gift for annoying everyone equally.",
  "Your secrets are safe with me. I never even listen when you talk.",
  "You're like a software update—always popping up and never useful.",
  "You're the human version of a broken charger.",
  "You bring absolutely nothing to the table. Not even napkins.",
  "You're like a black hole—no light, no hope, just emptiness.",
  "You're not lazy, you're just on energy-saving mode permanently.",
  "You have the personality of wet cardboard.",
  "You glow… like a broken microwave.",
  "You're about as useful as a screen door on a submarine.",
  "You're a few fries short of a Happy Meal.",
  "Your existence is a full-time jump scare.",
  "You're like a YouTube ad—unwanted and can't be skipped.",
  "You're more irrelevant than Internet Explorer.",
  "You're like a participation trophy—just there, doing nothing.",
  "You're living proof evolution can go in reverse.",
  "You have all the right tools to be annoying.",
  "Your brain’s Wi-Fi signal must be weak.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're less organized than a Windows Vista update.",
  "You make onions cry.",
  "You're like Monday morning—nobody likes you.",
  "You're a failed captcha test in human form.",
  "You're not even a has-been, you’re a never-was.",
  "You're the budget version of someone cooler.",
  "Your voice is like a dial-up modem dying.",
  "You're a human snooze button.",
  "You failed at being basic.",
  "You're not even original at being annoying.",
  "You're like expired milk—sour and unnecessary.",
  "You're the glitch in the matrix nobody wanted.",
  "You're the dictionary definition of ‘Why though?’",
  "You're the loading spinner of conversations.",
  "You're not weird. You're just poorly made.",
  "You're a walking Wi-Fi dead zone.",
  "You're like a pop-up ad, and just as irritating.",
  "You're a downgrade to silence.",
  "You're the type to lose a staring contest with a mirror.",
  "You're not a vibe, you're a virus.",
  "You're the pre-installed app nobody uses.",
  "You're the reason batteries aren’t included.",
];
